project:
  type: website

website:
  title: "GEO511_FinalProject_GURSOY"
  navbar:
    left:
      - href: index.qmd
        text: HOME
      - about.qmd

format:
  html:
    theme: cosmo
    includes:
        after_body: include/after_body.html
